version: "3.7"
services:
  golang:
    container_name: go_app
    image: golang:alpine
    build:
      context: .
      dockerfile: Dockerfile-go
    ports:
      - 8181:8080
    networks:
      - go_elastic
  elasticsearch:
    container_name: es_go
    image: bitnami/elasticsearch:latest
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ./.docker/elasticsearch/data:/bitnami/elasticsearch/data
    networks:
      - go_elastic
    ports:
      - 9200:9200
networks:
  go_elastic: